## http请求地址和配置文件映射: 
#/{application}/{profile}[/{label}] 映射 /[{label}/]{application}-{profile}.yml(或.properties)
#{application} 映射 客户端的spring.application.name
#{profile} 映射 客户端的spring.cloud.config.profile
#{label} 映射 客户端的spring.cloud.config.label

server:
  port: 9040

spring:
  application:
    #应用名
    name: springcloud-config-server
  profiles:
    #使用本地文件系统
    #active: native
    #使用git远程仓库
    active: git
  cloud:
    config:
      server:
        git:
          #git仓库地址
          uri: https://github.com/toforo/test-springcloud
          #git仓库账号密码(公共仓库不用填)
          #username: toforo
          #password: ******
          #配置文件所在目录
          search-paths: /springcloud/springcloud-config-server/src/main/resources/master
      #配置仓库分支
      label: master

#加入注册中心,实现高可用
eureka:
  instance:
    #实例标识
    instance-id: config-server
    #显示主机ip
    prefer-ip-address: true
  client: 
    service-url: 
      #defaultZone: http://127.0.0.1:9000/eureka/
      defaultZone: http://test:123456@127.0.0.1:9000/eureka/
